#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$#" -eq 0 ]; then
   read setpoint < "$DIR/setpoint" 
   datestr="$(date +"%F-%T:")"
   echo "$datestr Setpoint: $setpoint" >&2; exit 1
fi

re='^[0-9]+([.][0-9]+)?$'
if ! [[ $1 =~ $re ]] ; then
   echo "ERROR: Setpoint must be a number" >&2; exit 1
fi

echo $1 >  "$DIR/setpoint"
read setpoint <  "$DIR/setpoint"
datestr="$(date +"%F-%T:")"
echo "$datestr Setpoint: $setpoint" >>  /var/log/control_temp.log
echo "$datestr Setpoint: $setpoint" 



