#! /bin/bash

# Control setpoint (stored in file 'setpoint') for use with temperature controller

# SYNTAX: ./settemp [<setpoint>]

# EXAMPLE CALLS
# ./settemp 20.5

# INPUTS
# Optionally specify setpoint in degrees (C) as a float or integer to set new setpoint
# If no input argument specified, reads back current setpoint
# Uses configured location for setpoint file and logfile in /etc/controller.conf (this will take precedence) if not present config/controller.conf will be used
# If neither config file exists or contains setpoint location, the directory in which script is located will be used for setpoint file

# OUTPUTS
# Returns current/newly set setpoint to STDOUT and configured controller logfile with timestamps

# Changelog
# 2014 - First Version
# 06/2020 - Improved error handling and configuration from file, updated config keys

# Copyright (C) 2014, 2020 Aaron Lockton

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Allow all group users to write to files created by this script
umask 002

# Set default working directory same as this script location (containing setpoint file)
WORKING_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# See if WORKING_DIR is set in config file, /etc always takes precedence
if [[ -s /etc/controller.conf ]]; then
  source "/etc/controller.conf"
elif [[ -s config/controller.conf ]]; then
  # Try relative path if being run straight from repo- only works if running from repo root
  source "config/controller.conf"
fi

DIR="${WORKING_DIR}"

# If no arguments are specified, read current setpoint and exit
if [ "$#" -eq 0 ]; then
  if [[ -s "$DIR/setpoint" ]]; then
    read setpoint < "$DIR/setpoint"
    datestr=$(date -u +"%F-%T:")
    echo "$datestr Setpoint: $setpoint" >&2; exit 0
  else
    echo "ERROR: cannot find setpoint file $DIR/setpoint or file is empty, and no new setpoint specified"
    exit 1
  fi
fi

# If setpoint is specified, check it's a valid float
re='^[0-9]+([.][0-9]+)?$'
if ! [[ "${1}" =~ $re ]] ; then
  echo "ERROR: Setpoint must be a number" >&2; exit 1
fi

if [[ ! -d ${DIR} ]]; then
  echo "ERROR: Specified working directory ${DIR} does not exist - cannot create setpoint file" >&2; exit 1
fi

# Write new setpoint to setpoint file
echo "${1}" >  "$DIR/setpoint"
read setpoint <  "$DIR/setpoint"
datestr=$(date -u +"%F-%T:")
# If log is specified in config file, output to log as well as STDOUT
if [[ ! -z "${CONTROLLER_LOGFILE}" ]]; then
  echo "$datestr Setpoint: $setpoint" >>  "${CONTROLLER_LOGFILE}"
  if [[ $? -ne 0 ]]; then
    echo "WARNING: Cannot open / write to logfile ${CONTROLLER_LOGFILE} - check filename is correct and permissions?"
  fi
fi
echo "$datestr Setpoint: $setpoint"
