#! /bin/bash

# Control setpoint (stored in file 'setpoint') for use with temperature controller

# Set default working directory same as this script location (containing setpoint file)
WorkingDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# See if WorkingDir is set in config file, /etc always takes precedence
if [[ -s /etc/controller.conf ]]; then
  source "/etc/controller.conf"
elif [[ -s config/controller.conf ]]; then
  # Try relative path if being run straight from repo- only works if running from repo root
  source "config/controller.conf"
fi

DIR="${WorkingDir}"

# If no arguments are specified, read current setpoint and exit
if [ "$#" -eq 0 ]; then
  if [[ -s "$DIR/setpoint" ]]; then
    read setpoint < "$DIR/setpoint"
    datestr="$(date +"%F-%T:")"
    echo "$datestr Setpoint: $setpoint" >&2; exit 0
  else
    echo "ERROR: cannot find setpoint file $DIR/setpoint or file is empty, and no new setpoint specified"
    exit 1
  fi
fi

# If setpoint is specified, check it's a valid float
re='^[0-9]+([.][0-9]+)?$'
if ! [[ "${1}" =~ $re ]] ; then
  echo "ERROR: Setpoint must be a number" >&2; exit 1
fi

# Write new setpoint to setpoint file
echo "${1}" >  "$DIR/setpoint"
read setpoint <  "$DIR/setpoint"
datestr="$(date +"%F-%T:")"
# If log is specified in config file, output to log as well as STDOUT
if [[ ! -z "${ControllerLogfile}" ]]; then
  echo "$datestr Setpoint: $setpoint" >>  "${ControllerLogfile}"
fi
echo "$datestr Setpoint: $setpoint"
